apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pockey
resources:
- ../../../base/pockey-api-server


patches:
- path: deployment-patch.yaml
  target:
    kind: Deployment
    name: pockey-api-server
- path: configmap-patch.yaml
  target:
    kind: ConfigMap
    name: pockey-api-server-config

images:
- name: harbor.kyojs.com/tjsry0466/pockey-api-server-dev
  newTag: 407f9c436ae8ea01ef131f6c062ef6c9af748609
