apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pockey
resources:
- ../../../base/pockey-api-server


patches:
- path: deployment-patch.yaml
  target:
    kind: Deployment
    name: pockey-api-server
- path: configmap-patch.yaml
  target:
    kind: ConfigMap
    name: pockey-api-server-config

images:
- name: harbor.kyojs.com/tjsry0466/pockey-api-server-dev
  newName: fd3fb6bbdb9c5e1dc67381d0ef1b709bb0aa341e
