apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pockey
resources:
- ../../../base/pockey-api-server


patches:
- path: deployment-patch.yaml
  target:
    kind: Deployment
    name: pockey-api-server
- path: configmap-patch.yaml
  target:
    kind: ConfigMap
    name: pockey-api-server-config

images:
- name: harbor.kyojs.com/tjsry0466/pockey-api-server-dev
  newTag: 4fb3eef6e2906e59cad8d6f75dc8398efb7dcc58
