apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- configmap.yaml
- sealed-secret.yaml
- external-name-service.yaml

images:
- name: harbor.kyojs.com/tjsry0466/pockey-api-server-dev
  newName: TAG_IMAGE